threadtest.o: threadtest.cc \
 /home/uga/benjamin.grande2/kos/src/user/../testoptions.h \
 /home/uga/benjamin.grande2/kos/src/user/../include/syscalls.h \
 /home/uga/benjamin.grande2/kos/src/user/../include/kostypes.h \
 /home/uga/benjamin.grande2/kos/src/user/../include/pthread.h \
 /home/uga/benjamin.grande2/kos/src/user/../include/syscalls.h
systest.o: systest.cc \
 /home/uga/benjamin.grande2/kos/src/user/../testoptions.h \
 /home/uga/benjamin.grande2/kos/src/user/../include/syscalls.h \
 /home/uga/benjamin.grande2/kos/src/user/../include/kostypes.h
manythread.o: manythread.cc \
 /home/uga/benjamin.grande2/kos/src/user/../testoptions.h \
 /home/uga/benjamin.grande2/kos/src/user/../include/syscalls.h \
 /home/uga/benjamin.grande2/kos/src/user/../include/kostypes.h \
 /home/uga/benjamin.grande2/kos/src/user/../include/pthread.h \
 /home/uga/benjamin.grande2/kos/src/user/../include/syscalls.h
kbloop.o: kbloop.cc \
 /home/uga/benjamin.grande2/kos/src/user/../testoptions.h
