libKOS.o: libKOS.cc \
 /home/uga/benjamin.grande2/kos/src/ulib/../testoptions.h \
 /home/uga/benjamin.grande2/kos/src/ulib/../include/syscalls.h \
 /home/uga/benjamin.grande2/kos/src/ulib/../include/kostypes.h
pthread.o: pthread.cc \
 /home/uga/benjamin.grande2/kos/src/ulib/../testoptions.h \
 /home/uga/benjamin.grande2/kos/src/ulib/../include/syscalls.h \
 /home/uga/benjamin.grande2/kos/src/ulib/../include/kostypes.h \
 /home/uga/benjamin.grande2/kos/src/ulib/../include/pthread.h \
 /home/uga/benjamin.grande2/kos/src/ulib/../include/syscalls.h
